import { useEffect, useState } from "react";
import { RefreshCcw, LogOut, Cpu, Sun, Moon } from "lucide-react";
import { Button } from "../components/Button";
import { api } from "../services/api";
import { useAuth } from "../services/AuthContext";
import { useToast } from "../services/toast";
import type { Period } from "../types/api";
interface Props { title:string; description?:string; period?:Period; onPeriodChange?:(p:Period)=>void; onRefresh?:()=>void; loading?:boolean; }
const periods:[Period,string][]=[["today","Today"],["7d","7 days"],["30d","30 days"],["all","All time"]];
export function TopBar({title,description,period,onPeriodChange,onRefresh,loading}:Props){const {user,signOut}=useAuth();const toast=useToast();const [health,setHealth]=useState("unknown");const [theme,setTheme]=useState(localStorage.getItem("rim-theme")||"dark");useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);useEffect(()=>{let live=true;const check=()=>api.health().then(()=>live&&setHealth("ok")).catch(()=>live&&setHealth("down"));void check();const id=window.setInterval(check,30000);return()=>{live=false;window.clearInterval(id)}},[]);return <header className="topbar"><div className="topbar__title"><h1>{title}</h1>{description&&<p className="topbar__description">{description}</p>}</div><div className="topbar__controls">{onPeriodChange&&period&&<div className="topbar__period">{periods.map(([v,l])=><button key={v} className={`topbar__period-btn${period===v?" topbar__period-btn--active":""}`} onClick={()=>onPeriodChange(v)} type="button">{l}</button>)}</div>}<div className="topbar__meta"><span className={`topbar__health topbar__health--${health}`}><Cpu size={14}/>{health==="ok"?"API online":health==="down"?"API unreachable":"Checking…"}</span>{onRefresh&&<Button size="sm" variant="secondary" onClick={onRefresh} disabled={loading}><RefreshCcw size={14}/>Refresh</Button>}<Button size="sm" variant="ghost" onClick={()=>{const n=theme==="light"?"dark":"light";setTheme(n);localStorage.setItem("rim-theme",n)}}>{theme==="light"?<Moon size={14}/>:<Sun size={14}/>}</Button>{user&&<div className="topbar__user"><span className="topbar__avatar">{user.name.slice(0,2).toUpperCase()}</span>{user.name}</div>}<Button size="sm" variant="ghost" onClick={()=>void signOut().then(()=>toast.show("info","Signed out","Your session has ended."))}><LogOut size={14}/>Sign out</Button></div></div></header>}
