import { useState, type FormEvent } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { Eye, EyeOff, Sparkles } from "lucide-react";
import { Button } from "../components/Button";
import { useAuth } from "../services/AuthContext";

export function LoginPage({ registerMode = false }: { registerMode?: boolean }) {
  const { signIn, register } = useAuth();
  const navigate = useNavigate(); const location = useLocation();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState("");
  const [show, setShow] = useState(false); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); if (registerMode && password !== confirm) { setError("Passwords do not match."); return; } setLoading(true); try { if (registerMode) await register(name, email, password); else await signIn(email, password); navigate("/overview", { replace: true, state: location.state }); } catch (err) { setError(err instanceof Error ? err.message : "Unable to continue."); } finally { setLoading(false); } }
  return <div className="login"><div className="login__card"><div className="login__brand"><div className="login__logo">R</div><div><div className="login__brand-name">Rim</div><div className="login__brand-sub">ADMIN CONSOLE</div></div></div><h1 className="login__title">{registerMode ? "Create your account" : "Welcome back"}</h1><p className="login__description">{registerMode ? "Start managing your AI gateway with a secure Rim account." : "Sign in to your Rim workspace."}</p><form onSubmit={submit} className="login__form">{registerMode && <label className="form-field"><span className="form-field__label">Name</span><input className="form-field__input" required value={name} onChange={e => setName(e.target.value)} autoComplete="name" /></label>}<label className="form-field"><span className="form-field__label">Email</span><input className="form-field__input" required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" /></label><label className="form-field"><span className="form-field__label">Password</span><div className="form-field__input-wrapper"><input className="form-field__input form-field__input--with-icon" required minLength={8} type={show ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} autoComplete={registerMode ? "new-password" : "current-password"} /><button type="button" className="form-field__clear" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)}>{show ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></label>{registerMode && <label className="form-field"><span className="form-field__label">Confirm password</span><input className="form-field__input" required type="password" value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" /></label>}{error && <div className="login__error">{error}</div>}<Button variant="primary" type="submit" disabled={loading}><Sparkles size={16}/>{loading ? "Please wait…" : registerMode ? "Create account" : "Sign in"}</Button></form><div className="login__hint">{registerMode ? <>Already have an account? <Link to="/login">Sign in</Link></> : <>Don&apos;t have an account? <Link to="/register">Create account</Link></>}</div></div></div>;
}
